# Generated by Django 5.1.1 on 2024-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_alter_blood_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
